### ISSUE TITLE
support Python 3.10

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/GridDataFormats#101]
Enable testing for Python 3.10 (and fix anything that needs fixing).

**Comment by IAlibay** [comment]
Given the recent issues with `six` in the core library (highlighting this library as one of the core dependencies still requiring it), is it worth revisiting its use?

Looking at their issue tracker, I _think_ there's a fix for py3.10 for `six` but it's probably not coming for some time.

**Comment by orbeckst** [comment]
We can drop 2.7 and six if it creates issues.

**Comment by orbeckst** [comment]
Is six not working with 3.10?

if that’s the case then my comment in #102 to drop legacy for 1.0 is moot — we do want to support 3.10 asap.

**Comment by IAlibay** [comment]
I've not had time to really dig into it - there's a bunch of warnings that could be problematic, but it hasn't affected the outcome of the MDA testsuite, so whatever it's affecting isn't impacting most things probably?

**Comment by IAlibay** [comment]
I _think_ six is now working again with py3.10 (see v1.16.0 in https://github.com/benjaminp/six/blob/master/CHANGES).

As far as I can tell the six code isn't regularly tested with py3.10, but we can see what happens?
