### ISSUE TITLE
Question: outstanding issues for a 0.3.0 release?

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/GridDataFormats#15]
@kain88-de , are there any major outstanding issues?

Can we release the current state as 0.3.0?

**Comment by kain88-de** [comment]
I'd be nice to have a small testfile for gOpenMol and I maybe should change the tests in for the grid object to use an irregular shaped gird. But otherwise no.

**Comment by orbeckst** [comment]
Ok, then we'll do a 0.3.0 release with what we have and add onto that (e.g. with a 0.3.1).
I'll prepare the release today (I hope...).

**Comment by kain88-de** [comment]
Cool. Be sure to release it for Python3 as well ;)

**Comment by orbeckst** [comment]
Good point!!

On 22 Sep, 2015, at 12:55, kain88-de wrote:

> Cool. Be sure to release it for Python3 as well ;)

--
Oliver Beckstein * orbeckst@gmx.net
skype: orbeckst  * orbeckst@gmail.com

**Comment by orbeckst** [comment]
Released:

* https://pypi.python.org/pypi/GridDataFormats
* https://github.com/MDAnalysis/GridDataFormats/releases/tag/release-0.3.0

I added eggs for 2.7 and 3.4.

**Comment by kain88-de** [comment]
Could you maybe add wheels too? They are the new package-standard for a short time now. 

http://pythonwheels.com/

**Comment by orbeckst** [comment]
On 22 Sep, 2015, at 22:38, kain88-de wrote:

> Could you maybe add wheels too? They are the new package-standard for a short time now.
> 
> http://pythonwheels.com/

Can I make them with

	python setup.py build_wheel

??

--
Oliver Beckstein * orbeckst@gmx.net
skype: orbeckst  * orbeckst@gmail.com

**Comment by orbeckst** [comment]
I added a universal wheel package.

**Comment by kain88-de** [comment]
awesome thanks.
