### ISSUE TITLE
Parsing Speed

### ISSUE THREAD

**Issue by holocronweaver** [MDAnalysis/GridDataFormats#2]
I have been making great use of this package in my research, but as I recently graduated to 30 MB DX files I noticed the parsing time skyrocketed to the point of being almost unusuable.

Using the %prun command in ipython to load a several MB OpenDX file, I found the following culprits:

```
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
   149344    2.819    0.000    4.124    0.000 OpenDX.py:746(__tokenize)
        1    0.517    0.517    6.195    6.195 OpenDX.py:694(<listcomp>)
   448021    0.479    0.000    0.479    0.000 OpenDX.py:367(value)
   746754    0.401    0.000    0.401    0.000 OpenDX.py:360(__init__)
   448098    0.357    0.000    4.655    0.000 OpenDX.py:762(__refill_tokenbuffer)
   448049    0.351    0.000    5.199    0.000 OpenDX.py:783(__consume)
   746817    0.308    0.000    0.308    0.000 OpenDX.py:365(iscode)
```

Of these, the tokenizer is clearly public enemy number 1, though the total runtime was 6.24 seconds so the smaller inefficiencies add up to a greater whole.

I think moving the whole DXParser class to Cython is the easiest solution.  This is what pandas does for their pandas.read_\* series of parsers, and they are remarkably fast because of it.

Thoughts on this?  

It may be some time before I work on this, but I expect in a couple months I won't have much choice as my DX file sizes spiral out of control.

**Comment by kain88-de** [comment]
I don't think the problem is that the `__tokenize` function is especially slow. It's just called **a lot**.
But it doesn't need to be called on every line. Once we know that the data is coming there is no need to actual grammar parsing, we could directly feed all of that into the array. That should already save some time.
