### ISSUE TITLE
Import gridData fails

### ISSUE THREAD

**Issue by anuC** [MDAnalysis/GridDataFormats#20]
Hello, 

I recently installed GridDataFormats 0.3.0 through ' easy_install GridDataFormats-0.3.0-py2.7.egg ' . Unfortunately, when I try import the gridData module, its fails with the following error,

*************************************************************
$ python
Python 2.7.5 (default, Apr  9 2015, 11:03:32) 
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from gridData import Grid
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/GridDataFormats-0.3.0-py2.7.egg/gridData/__init__.py", line 191, in <module>
  File "/usr/lib/python2.7/site-packages/GridDataFormats-0.3.0-py2.7.egg/gridData/core.py", line 28, in <module>
ImportError: cannot import name range
>>>
****************************************************************

Can somebody help me to figure out what went wrong with  GridDataFormats installation?

Many thanks in advance
Anu

**Comment by kain88-de** [comment]
It looks like easy_install didn't install all our requirements. You need to install `six`. That is a package to write py2 and py3 compatible code. You can install it with

```
pip install --user six
```

It's a bit strange that easy_install didn't to that. But I'm not that experienced with easy_install and I don't know exactly what it does when you install from an egg.

**Comment by anuC** [comment]
Thanks for the reply. It looks to me like the six has already installed. 
$ pip install six
Requirement already satisfied (use --upgrade to upgrade): six in /usr/lib/python2.7/site-packages

Do I need to upgrade six here? or will there be some other problem?

Many thanks 
Anu

**Comment by kain88-de** [comment]
I guess that should do the trick but I'm a bit surprised that it doesn't work when six is already installed

Does `python -c 'from six.moves import range'` finish without errors on your machine?

**Comment by anuC** [comment]
Unfortunately, this time also the attempt failed with following error,

$ python -c 'from six.moves import range'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name range
$

**Comment by kain88-de** [comment]
Then something is wrong with your version of six. Try updating it. Also what version of python are you running.

**Comment by anuC** [comment]
Thanks for the reply. Everything going fine after I updated six to version 1.10.0. I am using python 2.7.5.

Many thanks
Anu
