### ISSUE TITLE
new 0.3.1. release soon

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/GridDataFormats#24]
With #21 fixed I would like to make a 0.3.1 bug fix release so that we can also address MDAnalysis/mdanalysis#544

Any opinions?

**Comment by kain88-de** [comment]
I have nothing against that since it is a severe issue. Normally I think we could publish new versions together with Mda

**Comment by orbeckst** [comment]
ok, then I'll make 0.3.1 soon-ish.

I don't think we have to sync releases with MDA because generally gridDataFormats is more slowly moving, we just have to make sure that we properly update version dependencies in MDA.

**Comment by orbeckst** [comment]
pushed the 0.3.1 release to PyPi
