### ISSUE TITLE
make scipy optional

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/GridDataFormats#25]
scipy is *not* installed by setup.py but nevertheless scipy is imported in such a way that `import gridData` fails without scipy.

Make sure that `import scipy` does not prevent importing of the package and give a sensible error message if functionality requiring scipy is used (the interpolation).

**Comment by orbeckst** [comment]
See also MDAnalysis/analysis#563.

**Comment by kain88-de** [comment]
We already do an interpolation when we initialize the `Grid` object. I haven't look to much into the actual logic of the `Grid` object so I don't know how easy it is to make this optional.

**Comment by orbeckst** [comment]
I just made it optional and the tests pass. 

--
Oliver Beckstein
email: orbeckst@gmail.com


Am Dec 11, 2015 um 16:22 schrieb kain88-de <notifications@github.com>:
