### ISSUE TITLE
gridDataFormats conda build

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/GridDataFormats#27]
Make package available in anaconda so that it can be pulled by *mdanalysis*. See MDAnalysis/mdanalysis#608 for details.

**Comment by kain88-de** [comment]
It should be possible to use the stuff from https://github.com/MDAnalysis/mdanalysis/pull/571 to build and push GridDataFormats to conda

**Comment by orbeckst** [comment]
@richardjgowers I made you the owner because it needs to be handled together with MDAnalysis/mdanalysis#608.
