### ISSUE TITLE
release 0.3.3

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/GridDataFormats#32]
It would be nice to cut a new release for the conda package. This is mainly including the tempdir package now and having conda build scripts. This is for the new MDAnalysis release where we also included tempdir.

I can prepare the conda packages and change the version string of the files. But I don't know how to change releases on github.

**Comment by kain88-de** [comment]
@orbeckst do you have time to do this?

**Comment by orbeckst** [comment]
Yes, just let me know I'd there's anything special to be done. 

Should be able to get to it tomorrow. 

Will you do conda?

--
Oliver Beckstein
email: orbeckst@gmail.com


Am May 12, 2016 um 2:25 schrieb kain88-de <notifications@github.com>:

**Comment by kain88-de** [comment]
Yes I will do the conda release.

**Comment by orbeckst** [comment]
* release [v0.3.3](https://github.com/MDAnalysis/GridDataFormats/releases/tag/release-0.3.3)
* uploaded distributions (tar.gz, egg, wheel) to [PyPi: GridDataFormats](https://pypi.python.org/pypi/GridDataFormats)

**Comment by kain88-de** [comment]
Anaconda release https://anaconda.org/MDAnalysis/griddataformats/files
