### ISSUE TITLE
Grid parsing error (non-standard format)

### ISSUE THREAD

**Issue by amrhamedp** [MDAnalysis/GridDataFormats#46]
Hello,
I have dx grid file that pymol and vmd can read but has many problems with other programs.
I tried to read it via gridataformat and write it again but parser has error 

https://transfer.sh/9GggU/chopped_48.dx

raise DXParseError('array: '+str(tok)+' not recognized.')

Can anyone help me please?
```python
from gridData import Grid
g = Grid("chopped_48.dx")
g.export("density1.dx")
```

**Comment by orbeckst** [comment]
Hi @amrhamedp , sorry for the delay in responding.

1. What version of the library are you running,
```python
import gridData as gd
print(gd.__version__)
```
2. Are you running Python 2 or Python 3?

The latest release is 0.4.0. When I use that release (under Python 3 and on macOS) with your example I have no problem writing a new dx file:
```python
>>> import gridData as gd
>>> print(gd.__version__)
0.4.0
>>> g = gd.Grid("chopped_48.dx")
>>> g.export("out.dx")
```

Attached is the density `out.dx` as rendered in Chimera and the gzipped file [out.dx.gz](https://github.com/MDAnalysis/GridDataFormats/files/1834639/out.dx.gz) (you can attach compressed files to issues):

![out.png](https://user-images.githubusercontent.com/237980/37728822-420df8f6-2d09-11e8-819c-ba186bc8d131.png)

**Comment by orbeckst** [comment]
@amrhamedp did you solve your problem?

I am going to close this issue in the next few days if there is no further feedback.

**Comment by orbeckst** [comment]
No more feedback, closing.
