### ISSUE TITLE
Python 3 

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/GridDataFormats#5]
Use [six](https://pypi.python.org/pypi/six) to support python 2 and 3 at the same time.

For the regexes you might want to choose [regex](https://pypi.python.org/pypi/regex). I can't find any information right now but I think I read somewhere that they also changed the `re` module in python3

**Comment by orbeckst** [comment]
Pull request welcome :-).

**Comment by kain88-de** [comment]
If you apply some test-data, or better tests. I have no personal experience with the dataformats this library supports neither have I any files to tests things.

**Comment by kain88-de** [comment]
There really isn't a lot I can do without some test-data. I haven't worked with any of the supported file 
formats so far and besides of the `dx` format I don't know from where I could get example data. Once I have some test-files I can look into having this run on Py3

**Comment by orbeckst** [comment]
I'll look for something... sorry, been rather busy.

**Comment by orbeckst** [comment]
I pasted a `water.dx` file as https://gist.github.com/orbeckst/4af8a8cfe721d1492256

**Comment by orbeckst** [comment]
Maybe gists are not ideal... unfortunately, I don't have small files at hand, so the following is probably only good for prototyping (download from dropbox):
* [water.plt](https://www.dropbox.com/s/s72bsfla8s7s2qq/water.plt?dl=0)  (PLT file, 24 MiB)
* [water_1.dx](https://www.dropbox.com/s/p3ch29x2cmufwa3/water_1.dx?dl=0) (DX file, 144 KiB) (this is the same as the gist above)

**Comment by orbeckst** [comment]
@kain88-de , also add yourself to AUTHORS.

**Comment by orbeckst** [comment]
Btw, does #8 make it actually work under Python 3?
If so, close this issue.

**Comment by kain88-de** [comment]
reading the dx files I had at hand worked.  So the Python 3 support is experimental but it works
