### ISSUE TITLE
Bug in CCP4.py

### ISSUE THREAD

**Issue by Digp** [MDAnalysis/GridDataFormats#57]
Hi guys! Great job with the package ;)
I just found a bug when reading a couple of .ccp4 files. The _header_struct object in the CCP4 class is reading "ncstart", "nrstart" and "nsstart" as unsigned integers ("I") when they should be signed integers ("i"). (Lines 180 and 181 in CCP4.py.)

In example: in the PDB structure 1jzv, the 2fo-fc/EDS map ([1jzv.ccp4](http://www.ebi.ac.uk/pdbe/coordinates/files/1jzv.ccp4)), "ncstart" is 4294967292 when it should be -4, and "nrstart" is 4294967273 when it should be -23.

Hope it helps!

Diego

**Comment by orbeckst** [comment]
Thanks @Digp. Sorry for the slow reply.

If you are comfortable with fixing the code then *please* [submit a pull request](http://makeapullrequest.com/).

**Comment by orbeckst** [comment]
@Digp many thanks for the great bug report. Sorry it took a while but this should now be fixed in the upcoming 0.4.1 release.
