### ISSUE TITLE
AttributeError: 'Grid' object has no attribute 'grid'

### ISSUE THREAD

**Issue by StefanGIT** [MDAnalysis/GridDataFormats#59]
Hi ,
while trying to multiply two grids, i get the following error:
```
  File "multipipsa/multipipsa.py", line 501, in runApbs
    visualizeGrid = potentialGrid * accesibilityGrid
  File "/exports/scratch/ana3/envs/mypipsa/lib/python2.7/site-packages/gridData/core.py", line 539, in __mul__
    return Grid(self.grid * _grid(other), edges=self.edges)
AttributeError: 'Grid' object has no attribute 'grid'
```
The relevant code lines are:
```
            potentialGrid = Grid(self.__data_dir+"/"+i+".dx")
            accesibilityGrid =Grid(self.__data_dir+"/"+i+".surf.dx")
            print(potentialGrid)
            print(accesibilityGrid)
            visualizeGrid = potentialGrid * accesibilityGrid
```
The error happens in the multiply?

**Comment by StefanGIT** [comment]
If i do the following:
            potentialGrid = Grid()
            potentialGrid.load(self.__data_dir+"/"+i+".dx")
            accesibilityGrid =Grid()
            accesibilityGrid.load(self.__data_dir+"/"+i+"_surf.dx")
            visualizeGrid = accesibilityGrid * potentialGrid

it works. Is there an issue with the Grid(filename) constructor?

**Comment by richardjgowers** [comment]
Hey @StefanGIT [this line](https://github.com/MDAnalysis/GridDataFormats/blob/master/gridData/core.py#L125) should make loading with a filename equivalent to your two step approach, but I think it's not working.

If you do `potentialGrid = Grid(str(self.__data_dir+"/"+i+".dx"))` does it make a difference?

**Comment by StefanGIT** [comment]
Thanks, the str(...) works as well!

**Comment by richardjgowers** [comment]
@StefanGIT what is your `self.__data_dir` object in this case?  A `pathlib` object?

**Comment by StefanGIT** [comment]
might be:
    cwd=os.getcwd()
    apbs = ApbsRun(**dataDir=cwd+"/example/pdbs"**,
                   temp=298.15,ios=0.100, structures=ingrp+outgrp)

**Comment by orbeckst** [comment]
The whole input autodetection code https://github.com/MDAnalysis/GridDataFormats/blob/8f40542c6f5184af8233dfc0cd2111e5d31a48d9/gridData/core.py#L127-L158 is pretty fragile and could do with a rework. At a minimum, we should not pass silently...
