### ISSUE TITLE
Wrong conversion from CCP4 to DX

### ISSUE THREAD

**Issue by nezix** [MDAnalysis/GridDataFormats#76]
#### Importing a CCP4 map to convert it to a DX file outputs an inverted DX file.

```python
from gridData import Grid
g = Grid("1cbs.ccp4")
g.export("1cbs.dx")
```

When displaying the DX file in Pymol or VMD, the molecule does not fit in the iso-surface

Level 1 of the exported DX file in Pymol:
![image](https://user-images.githubusercontent.com/9949327/70249818-3d98db00-177d-11ea-917d-b659e9b211db.png)

Level 1 of the CCP4 file in Pymol:
![image](https://user-images.githubusercontent.com/9949327/70249920-6620d500-177d-11ea-82a4-e16fbf8413ee.png)

 Did I miss something ?

**Comment by orbeckst** [comment]
That looks wrong... do you have an example file that you can add to the issue or link?

**Comment by nezix** [comment]
You can find the ccp4 file here https://www.ebi.ac.uk/pdbe/coordinates/files/1cbs.ccp4

**Comment by orbeckst** [comment]
I can confirm this bug.

Furthermore, the DX density appears to be stretched (see Chimera image, contours at 0.362)
- gray: [1cbs.ccp4](https://www.ebi.ac.uk/pdbe/coordinates/files/1cbs.ccp4)
- yellow: DX file from gridDataFormats
- licorice (barely visible) [1cbs.pdb](https://www.rcsb.org/structure/1CBS)

![1cbs_ccp4_dx](https://user-images.githubusercontent.com/237980/74881049-d3c6b100-5329-11ea-9d1d-e28ea02c792f.png)

**Comment by orbeckst** [comment]
Do we know if the problem is with 
- CCP4 reading
- CCP4 interpretation (conversion to Grid)
- something else (probably not DX writing because that's been used widely)

**Comment by orbeckst** [comment]
PR #100 does not fix this bug. In ChimeraX loading the densities gives
* CCP4 file: 81 x 70 x 96
* dx file: 70 x 81 x 96

Clearly there's something wrong in how gridData interprets the data in some(?) CCP4 files.
