### ISSUE TITLE
CCP4 file format is out of date

### ISSUE THREAD

**Issue by tluchko** [MDAnalysis/GridDataFormats#83]
The most recent MRC/CCP4 file format is available at https://www.ccpem.ac.uk/mrc_format/mrc2014.php, which is a significant update from the format used in gridDataFormats.  CCP-EM maintains a Python library for reading, writing and validating MRC2014 files at https://github.com/ccpem/mrcfile.  A simple option is to use this library for reading *and* writing but this would add an external dependency to gridDataFormats.

I'd be happy to add in support for reading and writing MRC2014 files by using the `mrcfile` module or update the existing code (which would be read-only support).  Is there a preference?

**Comment by orbeckst** [comment]
Does mrcfile have pip and conda installable packages?

**Comment by tluchko** [comment]
Yes. It has both pip and Conda packages.

```
pip install mrcfile
```

and

```
conda install --channel conda-forge mrcfile
```

**Comment by orbeckst** [comment]
We'd use mrcfile – no need to reinvent the wheel and it's a light-weight dependency.

If you could create a PR then that would be fantastic! Just ping me when you need a review. (And don't forget to add yourself to AUTHORS.)

**Comment by tluchko** [comment]
OK.  I haven't started anything yet, so I don't have a clear idea when this will be ready.

**Comment by orbeckst** [comment]
Maybe using mrcfile would help with fixing #76 ?

**Comment by orbeckst** [comment]
@tluchko , PR #100 uses mrcfile. Thank you for the suggestion.

I'd appreciate a code review of PR #100 if you have the time. Thanks.
