### ISSUE TITLE
MAINT: Switch from Travis to Github actions for CI

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/GridDataFormats#86]
Follow up from: https://github.com/MDAnalysis/mdanalysis/issues/3036

As our Travis allocation is organisation wide, it might be best to switch over to Github actions where possible.

**Comment by orbeckst** [comment]
Will also fix #85 ...

**Comment by orbeckst** [comment]
If we're doing any hacking/fixing on gridDataFormats then switching to GH actions is high on the list of priorities.

(Sounds like an excellent procrastination target...)
