### ISSUE TITLE
The double quotation mark in DX file format cannot be read by APBS

### ISSUE THREAD

**Issue by xiki-tempula** [MDAnalysis/GridDataFormats#87]
I'm using this package to write DX files for APBS input.
I noticed that it will write

`object 3 class array type "double" rank 0 items 912673 data follows`

However, the APBS don't like the double quotation mark around the `"double"`.
and would only recognise

`object 3 class array type double rank 0 items 912673 data follows`

I wonder if this double quotation mark is important for other software?

My script is the standard way of writing the grid file

```
        g = Grid(diel, origin=origin_x, delta=delta)
        g.export('diel.dx')
```

I think it is due to this command

https://github.com/MDAnalysis/GridDataFormats/blob/be6132ac13041390a880061e4e873044b6c29573/gridData/OpenDX.py#L384

where the self.typequote adds the double quotation mark.

**Comment by giacomofiorin** [comment]
That change is from #58. The quotation marks were added before, but that change made them *optional* to support some parsers. Didn't realize that this included APBS itself, so perhaps the quotation marks may be off by default.

You can get the desired output using:
```
g.export('diel.dx', typequote='')
```
which you would have also found out if you had typed `help(g.export)`.

**Comment by xiki-tempula** [comment]
Thank you.
