### ISSUE TITLE
Use scientific notation for the delta representation

### ISSUE THREAD

**Issue by xiki-tempula** [MDAnalysis/GridDataFormats#88]
I'm interested in using GridDataFormats to generate input OpenDX grid for APBS calculations.
For box dimensions of (90, 90, 150) with 257 data points in each direction.
The APBS will give the header:

```
object 1 class gridpositions counts 257 257 257
origin -4.500000e+01 -4.500000e+01 -7.500000e+01
delta 3.515625e-01 0.000000e+00 0.000000e+00
delta 0.000000e+00 3.515625e-01 0.000000e+00
delta 0.000000e+00 0.000000e+00 5.859375e-01
object 2 class gridconnections counts 257 257 257
```

The GridDataFormats will give the header

```
object 1 class gridpositions counts  257 257 257
origin -45.000000 -45.000000 -75.000000
delta  0.351562 0.000000 0.000000
delta  0.000000 0.351562 0.000000
delta  0.000000 0.000000 0.585938
object 2 class gridconnections counts  257 257 257
```

Since the GridDataFormats will give one less digit in the delta section, the OpenDX grid is rejected by the APBS. 

This easily be solved by changing
https://github.com/MDAnalysis/GridDataFormats/blob/be6132ac13041390a880061e4e873044b6c29573/gridData/OpenDX.py#L244
to 

`file.write('delta '+self.ndformat(' {:.6e}').format(*delta) +'\n')`

but I'm not sure if this will break other things.

**Comment by IAlibay** [comment]
Probably worth asking - which of the two adheres to the OpenDX standard and/or are both accepted by the standard and GridDataFormats & APBS doesn't support one of the two ways?

**Comment by xiki-tempula** [comment]
@IAlibay I don't know if OpenDX is still live or not.
I cannot open http://www.opendx.org/ and https://web.archive.org/web/20080808140524/http://opendx.sdsc.edu/docs/html/pages/usrgu068.htm didn't mention this.

**Comment by orbeckst** [comment]
What is the APBS error message?

**Comment by xiki-tempula** [comment]
The error message is 
```
Parsing input file lipid.in...
Parsed input file.
Got paths for 1 molecules
Reading PQR-format atom data from ref.pqr.
asc_getToken: Error occurred (bailing out).
Vio_scanf: Format problem with input.
  1 atoms
  Centered at (0.000e+00, 0.000e+00, 0.000e+00)
  Net charge -1.00e+00 e
Got paths for 1 dielectric map sets
Reading x-shifted dielectric map data from dielx.dx:
  257 x 257 x 257 grid
  (0.351562, 0.351562, 0.585938) A spacings
  (-44.8242, -45, -75) A lower corner
  Volume integral = 7.64e+07 A^3
Reading y-shifted dielectric map data from diely.dx:
  257 x 257 x 257 grid
  (0.351562, 0.351562, 0.585938) A spacings
  (-45, -44.8242, -75) A lower corner
  Volume integral = 7.64e+07 A^3
Reading z-shifted dielectric map data from dielz.dx:
  257 x 257 x 257 grid
  (0.351562, 0.351562, 0.585938) A spacings
  (-45, -45, -74.707) A lower corner
  Volume integral = 7.64e+07 A^3
Got paths for 1 charge maps
Reading charge map data from charge.dx:
  257 x 257 x 257 grid
  (0.351562, 0.351562, 0.585938) A spacings
  (-45, -45, -75) A lower corner
  Charge map integral = 2.36e+01 e
Preparing to run 1 PBE calculations.
----------------------------------------
CALCULATION #1 (lipid): MULTIGRID
  Setting up problem...
  Vpbe_ctor:  Using max ion radius (0 A) for exclusion function
fillcoChargeMap:  Error -- fell off of charge map at (45, -45, -75)!
```
I think since the delta in z axis has been truncated to 0.585938 instead of 5.859375e-01. The final point is 0.585938 * 256 = 150.000128, which is larger than the box dimension of 150.

**Comment by orbeckst** [comment]
So the problem is that the default precision is not high enough for some applications. 

Does APBS work if you write
```
object 1 class gridpositions counts  257 257 257
origin -45.000000 -45.000000 -75.000000
delta  0.3515625 0.000000 0.000000
delta  0.000000 0.3515625 0.000000
delta  0.000000 0.000000 0.5859375
object 2 class gridconnections counts  257 257 257
```
?

**Comment by orbeckst** [comment]
Do VMD and PyMOL read OpenDX files with engineering notation numbers?

**Comment by xiki-tempula** [comment]
@orbeckst 
I have verified that APBS does read in

```
object 1 class gridpositions counts  257 257 257
origin -45.000000 -45.000000 -75.000000
delta  0.3515625 0.000000 0.000000
delta  0.000000 0.3515625 0.000000
delta  0.000000 0.000000 0.5859375
object 2 class gridconnections counts  257 257 257
```

Sorry I haven't used Chimera/ChimeraX, but pymol and vmd would read the apbs output without a problem.

**Comment by orbeckst** [comment]
Maybe change the output format to `%g` ?

**Comment by orbeckst** [comment]
I am ok with increasing output precision to 7 or 8 digits, which would closer represent the _float_ in the OpenDX standard.
